name: Java CI with Maven

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - develop
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: cd gradehub && mvn -B package --file pom.xml  # ✅ Correct way to set working directory

    # Optional: Remove this if it still fails
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v4
