name: Java CI with Maven

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    branches:
      - main
      - develop
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'
        cache: maven

    - name: Debug - Show Repository Structure
      run: ls -R 

    - name: Build with Maven
      working-directory: Gradehub/Gradehub  
      run: mvn -B package --file pom.xml

    
    - name: Update dependency graph
      working-directory: Gradehub/Gradehub  
      uses: advanced-security/maven-dependency-submission-action@v4
